# Site settings
title: FritzTech Neuro
description: Ryan's Neurojourney
baseurl: "/Personal-Portfolio" # the subpath of your site, e.g. /blog/ or "" for the root domain
url: "https://fritztechneuro.github.io"

# Build settings
markdown: kramdown
theme: jekyll-theme-minimal

# Plugins
plugins:
  - jekyll-sitemap
  - jekyll-feed

# Exclude files/folders from build
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - config.yml
  - _config.yml
  - .github
  - .vscode
  - .gitignore
  - node_modules
  - vendor
  - .sass-cache
